<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="WeixinPublicNumber.aspx.cs" Inherits="Jiazhe.Web.Weixin.Admin.Pages.WeixinPublicNumber" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
    <style type="text/css">
        .gridView {
            width: 98%;
            height: 115px;
            position: absolute;
            top: 31px;
            left: 1%;
            right:1%;
            z-index: 1;
        }
        .gridViewItems {
        vertical-align:middle;
        text-align:center;
        height:24px;
        }
        .gridViewHeader {
        height:30px;
        background-color:navy;
        color:wheat;
        border:1px solid wheat;
        }
        .detailsView {
            width: 732px;
            height: 186px;
            position: absolute;
            top: 231px;
            left: 9px;
            z-index: 1;
            margin-top: 0px;
            right: 241px;
        }
        .detailsViewHeader {
            width:50px;
        text-align:right;
        }
        .detailsViewItems {
        }
    </style>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            <asp:Label ID="Label1" runat="server" Text="Label"></asp:Label>
        </div>
        <asp:Panel ID="Panel1" runat="server">
        <asp:GridView ID="GridViewWeixinPublic" runat="server" CssClass="gridView" AutoGenerateColumns="False" HeaderStyle-CssClass="gridViewHeader" AutoGenerateSelectButton="True" OnSelectedIndexChanged="GridViewWeixinPublic_SelectedIndexChanged">
            <Columns>
                <asp:BoundField DataField="WxId" HeaderText="序号" ItemStyle-CssClass="gridViewItems" >

                <ItemStyle CssClass="gridViewItems" />
                </asp:BoundField>

                <asp:BoundField DataField="WxName" HeaderText="微信名称" ItemStyle-CssClass="gridViewItems" >

                <ItemStyle CssClass="gridViewItems" />
                </asp:BoundField>

                <asp:BoundField DataField="WxNumber" HeaderText="微信号" ItemStyle-CssClass="gridViewItems" >

                <ItemStyle CssClass="gridViewItems" />
                </asp:BoundField>

                <asp:BoundField DataField="WxType" HeaderText="微信类型" ItemStyle-CssClass="gridViewItems" >

                <ItemStyle CssClass="gridViewItems" />
                </asp:BoundField>

                <asp:BoundField DataField="WxEmali" HeaderText="登录邮箱" ItemStyle-CssClass="gridViewItems" >

                <ItemStyle CssClass="gridViewItems" />
                </asp:BoundField>

                <asp:BoundField DataField="WxOriginalId" HeaderText="原始ID" ItemStyle-CssClass="gridViewItems" >
                <ItemStyle CssClass="gridViewItems" />
                </asp:BoundField>
                <asp:HyperLinkField HeaderText="基本配置" Text="详情" DataNavigateUrlFields="wxId" DataNavigateUrlFormatString="WeixinPublicNumberConfigure.aspx?wxId={0}" />
            </Columns>
            <HeaderStyle CssClass="gridViewHeader" />
        </asp:GridView></asp:Panel>

        <asp:Panel ID="Panel2" runat="server">
        <asp:DetailsView ID="DetailsViewWeixinPublic" runat="server" CssClass="detailsView" HeaderStyle-CssClass="detailsViewHeader" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateInsertButton="True" AutoGenerateRows="False" OnItemDeleting="DetailsViewWeixinPublic_ItemDeleting" OnItemInserting="DetailsViewWeixinPublic_ItemInserting" OnItemUpdating="DetailsViewWeixinPublic_ItemUpdating" OnModeChanging="DetailsViewWeixinPublic_ModeChanging">
            <Fields>
                <asp:BoundField DataField="WxId" HeaderText="序 号 ：" ItemStyle-CssClass="detailsViewItems" >
                <ControlStyle Width="50px" />
                <HeaderStyle HorizontalAlign="Right" />
                <ItemStyle CssClass="detailsViewItems" />
                </asp:BoundField>
                <asp:BoundField DataField="WxName" HeaderText="微信名称 ：" ItemStyle-CssClass="detailsViewItems" >
                 <ItemStyle CssClass="detailsViewItems" />
                </asp:BoundField>
                 <asp:BoundField DataField="WxNumber" HeaderText="微信号 ：" ItemStyle-CssClass="detailsViewItems" >
                 <ItemStyle CssClass="detailsViewItems" />
                </asp:BoundField>
                 <asp:BoundField DataField="WxEmali" HeaderText="登录邮箱 ：" ItemStyle-CssClass="detailsViewItems" >
                 <ItemStyle CssClass="detailsViewItems" />
                </asp:BoundField>
                 <asp:BoundField DataField="WxOriginalId" HeaderText="原始ID ：" ItemStyle-CssClass="detailsViewItems" >
                <ItemStyle CssClass="detailsViewItems" />
                </asp:BoundField>
            </Fields>
            <HeaderStyle CssClass="detailsViewHeader" />
        </asp:DetailsView></asp:Panel>

    </form>
</body>
</html>
